#[derive(Clone, Copy)]
pub enum MtZdoCommandId {
    ZdoNwkAddrReq = 0x00,
    ZdoIeeeAddrReq = 0x01,
    ZdoNodeDescReq = 0x02,
    ZdoPowerDescReq = 0x03,
    ZdoSimpleDescReq = 0x04,
    ZdoActiveEpReq = 0x05,
    ZdoMatchDescReq = 0x06,
    ZdoComplexDescReq = 0x07,
    ZdoUserDescReq = 0x08,
    ZdoEndDeviceAnnce = 0x0A,
    ZdoUserDescSet = 0x0B,
    ZdoServerDiscReq = 0x0C,
    ZdoEndDeviceBindReq = 0x20,
    ZdoBindReq = 0x21,
    ZdoUnbindReq = 0x22,
    ZdoMgmtNwkDiscReq = 0x30,
    ZdoMgmtLqiReq = 0x31,
    ZdoMgmtRtgReq = 0x32,
    ZdoMgmtBindReq = 0x33,
    ZdoMgmtLeaveReq = 0x34,
    ZdoMgmtDirectJoinReq = 0x35,
    ZdoMgmtPermitJoinReq = 0x36,
    ZdoMgmtNwkUpdateReq = 0x37,
    ZdoMsgCbRegister = 0x3E,
    ZdoMsgCbRemove = 0x3F,
    ZdoStartupFromApp = 0x40,
    ZdoStartupFromAppEx = 0x54,
    ZdoSetLinkKey = 0x23,
    ZdoRemoveLinkKey = 0x24,
    ZdoGetLinkKey = 0x25,
    ZdoNwkDiscoveryReq = 0x26,
    ZdoJoinReq = 0x27,
    // TODO - validate
    // ZDO_SET_REJOIN_PARAMETERS = 0x26,
    ZdoSecAddLinkKey = 0x42,
    ZdoSecEntryLookupExt = 0x43,
    ZdoSecDeviceRemove = 0x44,
    ZdoExtRouteDisc = 0x45,
    ZdoExtRouteCheck = 0x46,
    ZdoExtRemoveGroup = 0x47,
    ZdoExtRemoveAllGroup = 0x48,
    ZdoExtFindAllGroupsEndpoint = 0x49,
    ZdoExtFindGroup = 0x4A,
    ZdoExtAddGroup = 0x4B,
    ZdoExtCountAllGroups = 0x4C,
    ZdoExtRxIdle = 0x4D,
    ZdoExtUpdateNwkKey = 0x4E,
    ZdoExtSwitchNwkKey = 0x4F,
    ZdoExtNwkInfo = 0x50,
    ZdoExtSecApsRemoveReq = 0x51,
    ZdoForceConcentratorChange = 0x52,
    ZdoExtSetParams = 0x53,
    ZdoNwkAddrOfInterestReq = 0x29,
    // TODO - implement ParseByte
}

#[derive(Clone, Copy)]
pub enum MtZdoCallbackId {
    ZdoNwkAddrRsp = 0x80,
    ZdoIeeeAddrRsp = 0x81,
    ZdoNodeDescRsp = 0x82,
    ZdoPowerDescRsp = 0x83,
    ZdoSimpleDescRsp = 0x84,
    ZdoActiveEpRsp = 0x85,
    ZdoMatchDescRsp = 0x86,
    ZdoComplexDescRsp = 0x87,
    ZdoUserDescRsp = 0x88,
    ZdoUserDescConf = 0x89,
    ZdoServerDiscRsp = 0x8A,
    ZdoEndDeviceBindRsp = 0xA0,
    ZdoBindRsp = 0xA1,
    ZdoUnbindRsp = 0xA2,
    ZdoMgmtNwkDiscRsp = 0xB0,
    ZdoMgmtLqiRsp = 0xB1,
    ZdoMgmtRtgRsp = 0xB2,
    ZdoMgmtBindRsp = 0xB3,
    ZdoMgmtLeaveRsp = 0xB4,
    ZdoMgmtDirectJoinRsp = 0xB5,
    ZdoMgmtPermitJoinRsp = 0xB6,
    ZdoStateChangeInd = 0xC0,
    ZdoEndDeviceAnnceInd = 0xC1,
    ZdoMatchDescRspSent = 0xC2,
    ZdoStatusErrorRsp = 0xC3,
    ZdoSrcRtgInd = 0xC4,
    ZdoBeaconNotifyInd = 0xC5,
    ZdoJoinCnf = 0xC6,
    ZdoNwkDiscoveryCnf = 0xC7,
    ZdoLeaveInd = 0xC9,
    ZdoMsgCbIncoming = 0xFF,
    ZdoTcDevInd = 0xCA,
    ZdoPermitJoinInd = 0xCB,
    // TODO - implement ParseByte
}
